### ISSUE TITLE
Error setting up entry govee_lan for govee_lan

### ISSUE THREAD

**Issue by imacnu** [wez/govee-lan-hass#78]
Error setting up entry govee_lan for govee_lan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee_lan/__init__.py", line 33, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, component)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

Detected that custom integration 'govee_lan' sets option flow config_entry explicitly, which is deprecated at custom_components/govee_lan/config_flow.py, line 43: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/wez/govee-lan-hass/issues

**Comment by nateober** [comment]
This error is fixed in my fork: **https://github.com/nateober/govee-lan-hass**

The issue is that `async_forward_entry_setup` was removed in HA 2024.x (replaced with `async_forward_entry_setups`).

### Quick install via HACS:
1. HACS → Integrations → ⋮ menu → "Custom repositories"  
2. Add `https://github.com/nateober/govee-lan-hass` as Integration
3. Install and restart

PR submitted upstream: #81
